name: Package release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm ci
        working-directory: ./packages/roleplayer
      - run: npm test
        working-directory: ./packages/roleplayer

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: ./packages/roleplayer
      - run: npm publish
        working-directory: ./packages/roleplayer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
        working-directory: ./packages/roleplayer
      - run: npm publish
        working-directory: ./packages/roleplayer
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
